version: '3'
services:
  database:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    networks:
      - default


networks:
  default:
    external: true
    name: url-shortner